[package]
name = "boehm_gc"
version = "0.1.0"
authors = ["swgillespie <sean.william.g@gmail.com>"]

# We use the build script to discover what `-L` directive to
# provide to the linker  to link to the pre-installed GC.
build = "build.rs"
